
services:
  php:
    image: php:8.2-fpm-buster
    container_name: ecoride-php
    volumes:
      - ./src:/var/www/html
  
  web:
    image: nginx:latest
    container_name: ecoride_nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:80
    depends_on:
      - php
  db:
    image: mariadb:10.5
    container_name: ecoride_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecoride
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
